
	charmap "a", $80
	charmap "b", $81
	charmap "c", $82
	charmap "d", $83
	charmap "e", $84
	charmap "f", $85
	charmap "g", $86
	charmap "h", $87
	charmap "i", $88
	charmap "j", $89
	charmap "k", $8a
	charmap "l", $8b
	charmap "m", $8c
	charmap "n", $8d
	charmap "o", $8e
	charmap "p", $8f
	charmap "q", $90
	charmap "r", $91
	charmap "s", $92
	charmap "t", $93
	charmap "u", $94
	charmap "v", $95
	charmap "w", $96
	charmap "x", $97
	charmap "y", $98
	charmap "z", $99
	charmap "0", $9a
	charmap "1", $9b
	charmap "2", $9c
	charmap "3", $9d
	charmap "4", $9e
	charmap "5", $9f
	charmap "6", $a0
	charmap "7", $a1
	charmap "8", $a2
	charmap "9", $a3
	charmap "M", $a4
	charmap "E", $a5
	charmap "N", $a6
	charmap "U", $a7
	charmap "X", $b4
	charmap ".", $b5
	charmap "!", $b6
	charmap "?", $b7
	charmap " ", $b8
